spring:
  application:
    name: Diveni backend
  boot:
    admin:
      client:
        url: http://localhost:2222
        instance:
          metadata:
            service-host-type: IP
            user:
              name: user
              password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  info:
    env:
      enabled: true

logging:
  file:
    name: ./var/log/diveni-application.log
  pattern:
    # file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

.env:
  # directory: /
  filename: .env
  #  ignoreIfMalformed: true
  ignoreIfMissing: false
  systemProperties: true
  #  prefix: "env"

