name: Deploy Diveni

on:
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'proxy/**'
      - '.github/workflows/diveni-deploy.yml'
  workflow_dispatch:

jobs:
  docker-images:
    name: Docker-Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [backend, frontend, proxy]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Current service
        run: echo ${{ matrix.service }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify files changed
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ${{ matrix.service }}:
              - '${{ matrix.service }}/**'

      - name: Check if changes were made
        run: echo steps.filter.outputs.${{ matrix.service }}

      - name: Only running if changes were made
        run: echo "Changes were made"

      - name: Only running if changes were not made
        run: echo "Changes were not made"
