name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: Sybit-Education/Diveni
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm ci && npm run build
          BUILD_DIR: docs/.vuepress/dist/
